### ISSUE TITLE
Do we need `base_unit`?

### ISSUE THREAD

**Issue by thegedge** [Shopify/measured#34]
Discussion: does `Measured::Conversion.base_unit` add any value, or can we remove it to simplify the interface?

**Comment by kmcphillips** [comment]
We can look at removing it. It's there to allow resolution of the conversion tree. But we may be able to define an arbitrary base, rather than giving one explicitly.

**Comment by thegedge** [comment]
If that's all it's for, I'd love to drop it and simply use a graph traversal algorithm to resolve the conversion tree between every pair of units. Adds some extra work to a hidden portion of the library but simplifies our public interface.

**Comment by kmcphillips** [comment]
You can take a stab at it. Part of the complexity of this is that we want the shortest, and want to avoid any lossy conversions. So going `m -> cm -> mm` doesn't matter because you collapse them down to a single conversion factor. But if you end up `m -> in -> mm` you introduce lossyness by including an imperfect conversion factor when it is not necessary.

**Comment by thegedge** [comment]
I decided that we should perhaps stick with a base unit, because a lot of standards arounds units of measure define a measurement system as a base unit and derived units. Given we've said conversions are done via UCUM, it makes sense to stick to that.
